# .travis.yml
language: node_js

node_js:
  - '6'
  - '8'
  - '10'
  - '11'

before_script:
  - psql -c "create database objection_find_test;" -U postgres
  - mysql -e "create database objection_find_test;"

after_script:
  - npm run-script coveralls

notifications:
  email: false

addons:
  postgresql: '9.6'
